// Entity registry - the curated list of every primitive and component.
// Single source of truth for the gallery (entities.html). New primitives go
// in primitives.js, new components in components.js; register each here with
// a GENERIC schema. The gallery builds its controls from `opts` (no custom UI).
//
// Control field types:
//   number: <input type=number> with min/max/step
//   color:  <input type=color>  (value hex, converts to int 0xRRGGBB)
//   vector: <input type=text>   (comma-separated numbers -> array)
//   text:   <input type=text>   (free-form string)

import {
  createGround,
  createBox,
  createSphere,
  createCylinder,
  createRock,
  createTriangle,
  createPlayer,
  createHeart,
  createFlySwarm,
} from "./primitives.js";

import {
  createGrass,
  createRailSegment,
  createTrain,
  createDynamite,
  createCowcatcher,
  createBunny,
  createSign,
  createGatlingGun,
  createLawnmower,
  createButterfly,
  createDragonfly,
  createFlies,
} from "./components.js";

import { createPowerupsPreview } from "./powerups.js";
import { createSandBlast } from "./effects.js";

export const ENTRIES = [
  {
    category: "primitive",
    key: "ground",
    label: "Ground",
    desc: "Static planar platform",
    fn: createGround,
    opts: [
      {
        key: "size",
        label: "Size",
        type: "number",
        default: 6,
        min: 1,
        max: 30,
        step: 1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        default: 1,
        min: 0.2,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0x222233" },
      {
        key: "friction",
        label: "Friction",
        type: "number",
        default: 0.3,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "box",
    label: "Box",
    desc: "Interactable cube",
    fn: createBox,
    opts: [
      {
        key: "size",
        label: "Size",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0xff5533" },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 1,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "friction",
        label: "Friction",
        type: "number",
        default: 0.3,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "sphere",
    label: "Sphere",
    desc: "Rollable ball",
    fn: createSphere,
    opts: [
      {
        key: "radius",
        label: "Radius",
        type: "number",
        default: 0.5,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0x33aaff" },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 1,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "friction",
        label: "Friction",
        type: "number",
        default: 0.3,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "cylinder",
    label: "Cylinder",
    desc: "Tapered column",
    fn: createCylinder,
    opts: [
      {
        key: "radiusTop",
        label: "Radius Top",
        type: "number",
        default: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        key: "radiusBottom",
        label: "Radius Bottom",
        type: "number",
        default: 1,
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "radialSegments",
        label: "Radial Segments",
        type: "number",
        default: 8,
        min: 3,
        max: 32,
        step: 1,
      },
      { key: "color", label: "Color", type: "color", default: "0x88cc55" },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 1,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "friction",
        label: "Friction",
        type: "number",
        default: 0.3,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "rock",
    label: "Rock",
    desc: "Faceted jagged rock / boulder",
    fn: createRock,
    opts: [
      {
        key: "radius",
        label: "Radius",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0x6e7278" },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 10,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: "scale",
        label: "Scale [x,y,z]",
        type: "vector",
        default: [1, 0.8, 1],
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "triangle",
    label: "Triangle",
    desc: "Triangular wedge / ramp (cowcatcher)",
    fn: createTriangle,
    opts: [
      {
        key: "width",
        label: "Width",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0xcccccc" },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 1,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "player",
    label: "Player",
    desc: "Keyboard-controlled (WASD/Space)",
    fn: createPlayer,
    opts: [
      {
        key: "size",
        label: "Size",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0x22ff88" },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 5,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "speed",
        label: "Speed",
        type: "number",
        default: 10,
        min: 1,
        max: 40,
        step: 1,
      },
      {
        key: "jumpForce",
        label: "Jump Force",
        type: "number",
        default: 8,
        min: 1,
        max: 30,
        step: 1,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "heart",
    label: "Heart",
    desc: "A smooth, sculpted 3D heart with soft rounded curves",
    fn: createHeart,
    opts: [
      { key: "color", label: "Color", type: "color", default: "0xff3344" },
      {
        key: "scale",
        label: "Scale",
        type: "number",
        default: 1,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "mass",
        label: "Mass",
        type: "number",
        default: 1,
        min: 0,
        max: 50,
        step: 0.5,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "primitive",
    key: "flyswarm",
    label: "Fly Swarm",
    desc: "A group of flies zooming within a bounded sphere",
    fn: createFlySwarm,
    opts: [
      {
        key: "count",
        label: "Fly Count",
        type: "number",
        default: 10,
        min: 1,
        max: 60,
        step: 1,
      },
      { key: "color", label: "Color", type: "color", default: "0x1a1a1a" },
      {
        key: "size",
        label: "Fly Size",
        type: "number",
        default: 0.035,
        min: 0.005,
        max: 0.2,
        step: 0.005,
      },
      {
        key: "radius",
        label: "Swarm Radius",
        type: "number",
        default: 1.5,
        min: 0.2,
        max: 6,
        step: 0.1,
      },
      {
        key: "speed",
        label: "Speed",
        type: "number",
        default: 2,
        min: 0.5,
        max: 10,
        step: 0.5,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 1.2, 0],
      },
    ],
  },
  {
    category: "component",
    key: "grass",
    label: "Grass",
    desc: "A field of grass blades (component)",
    fn: createGrass,
    opts: [
      {
        key: "width",
        label: "Width",
        type: "number",
        default: 10,
        min: 1,
        max: 30,
        step: 1,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        default: 10,
        min: 1,
        max: 30,
        step: 1,
      },
      {
        key: "count",
        label: "Blade Count",
        type: "number",
        default: 200,
        min: 1,
        max: 500,
        step: 10,
      },
      { key: "color", label: "Color", type: "color", default: "0x44aa55" },
      {
        key: "height",
        label: "Height",
        type: "number",
        default: 1,
        min: 0.2,
        max: 4,
        step: 0.1,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "railsegment",
    label: "Rail Segment",
    desc: "A train-track chunk (rails + ties)",
    fn: createRailSegment,
    opts: [
      {
        key: "length",
        label: "Length",
        type: "number",
        default: 50,
        min: 10,
        max: 200,
        step: 5,
      },
      {
        key: "radius",
        label: "Radius (0=straight)",
        type: "number",
        default: 0,
        min: -50,
        max: 50,
        step: 1,
      },
      {
        key: "gauge",
        label: "Gauge",
        type: "number",
        default: 1.5,
        min: 0.5,
        max: 5,
        step: 0.1,
      },
      {
        key: "tieSpacing",
        label: "Tie Spacing",
        type: "number",
        default: 5,
        min: 1,
        max: 20,
        step: 1,
      },
      {
        key: "railColor",
        label: "Rail Color",
        type: "color",
        default: "0x9aa0a6",
      },
      {
        key: "tieColor",
        label: "Tie Color",
        type: "color",
        default: "0x6b4a32",
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "train",
    label: "Train",
    desc: "A steam locomotive composite (no physics)",
    fn: createTrain,
    opts: [
      {
        key: "bodyColor",
        label: "Body Color",
        type: "color",
        default: "0xc23b2e",
      },
      {
        key: "cabColor",
        label: "Cab Color",
        type: "color",
        default: "0x8a2b22",
      },
      {
        key: "accentColor",
        label: "Accent Color",
        type: "color",
        default: "0x334455",
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "cowcatcher",
    label: "Cowcatcher",
    desc: "A fan of skinny triangular wedges (component)",
    fn: createCowcatcher,
    opts: [
      {
        key: "count",
        label: "Count",
        type: "number",
        default: 6,
        min: 2,
        max: 20,
        step: 1,
      },
      {
        key: "width",
        label: "Tooth Width",
        type: "number",
        default: 0.32,
        min: 0.005,
        max: 0.5,
        step: 0.01,
      },
      {
        key: "gap",
        label: "Gap",
        type: "number",
        default: 0.16,
        min: 0,
        max: 0.5,
        step: 0.01,
      },
      {
        key: "depth",
        label: "Depth",
        type: "number",
        default: 2.2,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        default: 1.3,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      { key: "color", label: "Color", type: "color", default: "0x222b33" },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "dynamite",
    label: "Dynamite",
    desc: "A bundle of three long red dynamite sticks (component)",
    fn: createDynamite,
    opts: [
      {
        key: "length",
        label: "Length",
        type: "number",
        default: 2.4,
        min: 0.5,
        max: 6,
        step: 0.1,
      },
      {
        key: "radius",
        label: "Radius",
        type: "number",
        default: 0.18,
        min: 0.05,
        max: 1,
        step: 0.05,
      },
      { key: "color", label: "Color", type: "color", default: "0xd93a2b" },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "bunny",
    label: "Bunny",
    desc: "A cute bunny composed of spheres and ellipsoids (component)",
    fn: createBunny,
    opts: [
      { key: "color", label: "Color", type: "color", default: "0xffffff" },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "sign",
    label: "Sign",
    desc: "A cylindrical post with a rectangular signboard (component)",
    fn: createSign,
    opts: [
      {
        key: "postHeight",
        label: "Post Height",
        type: "number",
        default: 2.2,
        min: 0.5,
        max: 6,
        step: 0.1,
      },
      {
        key: "postRadius",
        label: "Post Radius",
        type: "number",
        default: 0.12,
        min: 0.05,
        max: 0.5,
        step: 0.01,
      },
      { key: "postColor", label: "Post Color", type: "color", default: "0x8a6d4b" },
      {
        key: "boardWidth",
        label: "Board Width",
        type: "number",
        default: 1.6,
        min: 0.2,
        max: 5,
        step: 0.1,
      },
      {
        key: "boardHeight",
        label: "Board Height",
        type: "number",
        default: 0.7,
        min: 0.2,
        max: 3,
        step: 0.1,
      },
      { key: "boardColor", label: "Board Color", type: "color", default: "0xffffff" },
      {
        key: "text",
        label: "Board Text",
        type: "text",
        default: "",
      },
      { key: "textColor", label: "Text Color", type: "color", default: "0x222222" },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "gatlinggun",
    label: "Gatling Gun",
    desc: "5-barrel rotating gun with start/stop controls",
    fn: createGatlingGun,
    opts: [
      {
        key: "barrelCount",
        label: "Barrel Count",
        type: "number",
        default: 5,
        min: 3,
        max: 12,
        step: 1,
      },
      {
        key: "barrelLength",
        label: "Barrel Length",
        type: "number",
        default: 3.0,
        min: 0.5,
        max: 8,
        step: 0.1,
      },
      {
        key: "barrelRadius",
        label: "Barrel Radius",
        type: "number",
        default: 0.06,
        min: 0.02,
        max: 0.3,
        step: 0.01,
      },
      {
        key: "speed",
        label: "Spin Speed",
        type: "number",
        default: 12,
        min: 1,
        max: 40,
        step: 0.5,
      },
      { key: "color", label: "Body Color", type: "color", default: "0x3a3a3e" },
      { key: "barrelColor", label: "Barrel Color", type: "color", default: "0x555558" },
      { key: "baseColor", label: "Mount Color", type: "color", default: "0x2a2a2e" },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
    actions: [
      { label: "Start", method: "start" },
      { label: "Stop", method: "stop" },
    ],
  },
  {
    category: "component",
    key: "lawnmower",
    label: "Lawnmower",
    desc: "A manual push lawnmower with reel blades and a handle",
    fn: createLawnmower,
    opts: [
      {
        key: "wheelRadius",
        label: "Wheel Radius",
        type: "number",
        default: 0.5,
        min: 0.2,
        max: 2,
        step: 0.05,
      },
      {
        key: "reelWidth",
        label: "Reel Width",
        type: "number",
        default: 1.0,
        min: 0.2,
        max: 3,
        step: 0.05,
      },
      {
        key: "bladeThickness",
        label: "Blade Thickness",
        type: "number",
        default: 0.03,
        min: 0.005,
        max: 0.2,
        step: 0.005,
      },
      {
        key: "blades",
        label: "Blade Count",
        type: "number",
        default: 4,
        min: 2,
        max: 10,
        step: 1,
      },
      {
        key: "handleAngle",
        label: "Handle Angle (rad)",
        type: "number",
        default: 0.55,
        min: 0,
        max: 1.4,
        step: 0.05,
      },
      {
        key: "handleLength",
        label: "Handle Length",
        type: "number",
        default: 1.5,
        min: 0.5,
        max: 3,
        step: 0.05,
      },
      {
        key: "reelRatio",
        label: "Reel:Wheel Ratio",
        type: "number",
        default: 2,
        min: 1,
        max: 8,
        step: 0.5,
      },
      { key: "bodyColor", label: "Handle Color", type: "color", default: "0x2a3d56" },
      { key: "bladeColor", label: "Blade Color", type: "color", default: "0xb8c2cc" },
      { key: "wheelColor", label: "Wheel Color", type: "color", default: "0x1a1a1a" },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
      {
        key: "rotation",
        label: "Rotation [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "component",
    key: "butterfly",
    label: "Butterfly",
    desc: "A flapping butterfly: tiny cylinder body + two triangle wings",
    fn: createButterfly,
    opts: [
      { key: "bodyColor", label: "Body Color", type: "color", default: "0x222222" },
      { key: "wingColor", label: "Wing Color", type: "color", default: "0xffb347" },
      {
        key: "wingSpan",
        label: "Wing Span",
        type: "number",
        default: 0.3,
        min: 0.1,
        max: 2,
        step: 0.05,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0.8, 0],
      },
    ],
  },
  {
    category: "component",
    key: "dragonfly",
    label: "Dragonfly",
    desc: "A fast-flapping dragonfly: slender body + two sets of rectangular wings",
    fn: createDragonfly,
    opts: [
      { key: "bodyColor", label: "Body Color", type: "color", default: "0x2a2a2a" },
      { key: "wingColor", label: "Wing Color", type: "color", default: "0xcfe8ff" },
      {
        key: "wingSpan",
        label: "Wing Span",
        type: "number",
        default: 0.4,
        min: 0.1,
        max: 2,
        step: 0.05,
      },
      {
        key: "wingTilt",
        label: "Wing Tilt (deg)",
        type: "number",
        default: -6,
        min: -45,
        max: 45,
        step: 1,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0.8, 0],
      },
    ],
  },
  {
    category: "component",
    key: "flies",
    label: "Flies",
    desc: "A swarm of tiny midges that dart from spot to spot",
    fn: createFlies,
    opts: [
      {
        key: "count",
        label: "Count",
        type: "number",
        default: 20,
        min: 1,
        max: 100,
        step: 1,
      },
      { key: "color", label: "Color", type: "color", default: "0x1a1a1a" },
      {
        key: "spread",
        label: "Spread",
        type: "number",
        default: 30,
        min: 1,
        max: 100,
        step: 1,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 0, 0],
      },
    ],
  },
  {
    category: "ux",
    key: "powerups",
    label: "Powerups",
    desc: "3 canned powerup pills preview",
    fn: createPowerupsPreview,
    opts: [],
    controls(form, getHandle) {
      const field = (label) => {
        const div = document.createElement("div");
        div.className = "field";
        const lab = document.createElement("label");
        lab.textContent = label;
        div.appendChild(lab);
        form.appendChild(div);
        return div;
      };

      // Background: transparent (none) or a solid color.
      const bgField = field("Background");
      const noneWrap = document.createElement("label");
      noneWrap.style.fontSize = "0.78rem";
      noneWrap.style.opacity = "0.8";
      noneWrap.style.display = "flex";
      noneWrap.style.alignItems = "center";
      noneWrap.style.gap = "6px";
      const noneBox = document.createElement("input");
      noneBox.type = "checkbox";
      noneBox.checked = true;
      const colorInput = document.createElement("input");
      colorInput.type = "color";
      colorInput.value = "#334466";
      colorInput.disabled = true;
      const applyBg = () =>
        getHandle()?.setBackground?.(
          noneBox.checked ? "none" : colorInput.value,
        );
      noneBox.addEventListener("change", () => {
        colorInput.disabled = noneBox.checked;
        applyBg();
      });
      colorInput.addEventListener("input", applyBg);
      noneWrap.appendChild(noneBox);
      noneWrap.appendChild(document.createTextNode("Transparent"));
      bgField.appendChild(noneWrap);
      bgField.appendChild(colorInput);

      // Show icons/glyphs.
      const iconField = field("Show icons");
      const iconBox = document.createElement("input");
      iconBox.type = "checkbox";
      iconBox.checked = true;
      iconBox.addEventListener("change", () =>
        getHandle()?.setShowIcon?.(iconBox.checked),
      );
      iconField.appendChild(iconBox);
    },
  },
  {
    category: "effect",
    key: "sandblast",
    label: "Sandblast",
    desc: "Directional sand jet particle emitter",
    fn: createSandBlast,
    opts: [
      {
        key: "particleCount",
        label: "Particle Count",
        type: "number",
        default: 500,
        min: 10,
        max: 2000,
        step: 10,
      },
      {
        key: "particleSize",
        label: "Particle Size",
        type: "number",
        default: 0.16,
        min: 0.01,
        max: 1.5,
        step: 0.01,
      },
      { key: "color", label: "Color", type: "color", default: "0xffd97d" },
      {
        key: "speed",
        label: "Speed",
        type: "number",
        default: 34,
        min: 1,
        max: 60,
        step: 0.5,
      },
      {
        key: "spread",
        label: "Spread",
        type: "number",
        default: 0.25,
        min: 0.05,
        max: 1.5,
        step: 0.05,
      },
      {
        key: "gravity",
        label: "Gravity",
        type: "number",
        default: 8,
        min: 0,
        max: 40,
        step: 1,
      },
      {
        key: "lifetime",
        label: "Lifetime",
        type: "number",
        default: 0.75,
        min: 0.1,
        max: 2.0,
        step: 0.05,
      },
      {
        key: "rate",
        label: "Spawn Rate",
        type: "number",
        default: 350,
        min: 10,
        max: 2000,
        step: 10,
      },
      {
        key: "position",
        label: "Position [x,y,z]",
        type: "vector",
        default: [0, 1.5, 0],
      },
      {
        key: "direction",
        label: "Direction [x,y,z]",
        type: "vector",
        default: [1, -0.15, 0],
      },
    ],
  },
];
